#!/bin/bash
# =============================================================================
# MOCK SWA AGENT — DEV/TEST ONLY — NOT FOR CUSTOMER USE
# =============================================================================
# Mimics: /opt/swa/bin/swa-agent api fetch jwt --audience <audience>
#
# Usage: Set SWA_AGENT_BIN to this script's path before running demo.sh
#   export SWA_AGENT_BIN=/path/to/setup/swa/mock_agent.sh
#
# This mock signs a JWT with a local RSA key pair generated by gen_mock_keys.sh.
# The Conjur JWT authenticator is configured with the matching public key
# via the public-keys variable (no HTTP JWKS server required).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRIVATE_KEY="$SCRIPT_DIR/mock_private.pem"

# --- Parse args: api fetch jwt --audience <value> ---
if [[ "${1:-}" != "api" || "${2:-}" != "fetch" || "${3:-}" != "jwt" ]]; then
  echo "Usage: swa-agent api fetch jwt --audience <audience>" >&2
  exit 1
fi

AUDIENCE="conjur"
while [[ $# -gt 3 ]]; do
  case "${4:-}" in
    --audience) AUDIENCE="${5:-conjur}"; shift 2 ;;
    *) shift ;;
  esac
done

# --- Validate private key exists ---
if [ ! -f "$PRIVATE_KEY" ]; then
  echo "ERROR: Mock private key not found: $PRIVATE_KEY" >&2
  echo "       Run setup.sh first to generate mock keys." >&2
  exit 1
fi

# --- JWT parameters ---
ISSUER="${SWA_MOCK_ISSUER:-https://mock.swa.local}"
SUBJECT="${SWA_WORKLOAD_ID:-swa-hello-world}"
DOMAIN="${SWA_DOMAIN:-spiffe://demo.local}"
TTL="${SWA_JWT_TTL:-600}"
NOW=$(date +%s)
EXP=$((NOW + TTL))
KID="mock-swa-key-1"

# --- Build JWT ---
b64url() {
  printf '%s' "$1" | base64 -w0 | tr -d '=' | tr '+/' '-_'
}

HEADER=$(b64url "{\"alg\":\"RS256\",\"typ\":\"JWT\",\"kid\":\"${KID}\"}")
PAYLOAD=$(b64url "{\"sub\":\"${SUBJECT}\",\"aud\":\"${AUDIENCE}\",\"iss\":\"${ISSUER}\",\"iat\":${NOW},\"exp\":${EXP},\"spiffe_id\":\"${DOMAIN}/${SUBJECT}\"}")

SIGNING_INPUT="${HEADER}.${PAYLOAD}"

SIG=$(printf '%s' "$SIGNING_INPUT" \
  | openssl dgst -sha256 -sign "$PRIVATE_KEY" \
  | base64 -w0 | tr -d '=' | tr '+/' '-_')

printf '%s.%s.%s\n' "$HEADER" "$PAYLOAD" "$SIG"
