apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-hardcoded.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql-hardcoded.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mysql-hardcoded.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql-hardcoded.fullname" . }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-hardcoded-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-hardcoded-pvc
        - name: initdb
          configMap:
            name: mysql-hardcoded-initdb
