apiVersion: v1
kind: Secret
metadata:
  name: mysql-hardcoded-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql-hardcoded.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
