terraform {
  required_providers {
    swa = {
      # Installed locally via setup/swa/install_tf_provider.sh
      source  = "registry.terraform.io/cyberark/swa"
      version = "0.1.0-SNAPSHOT"
    }
  }
}

provider "swa" {
  url          = var.conjur_url
  access_token = var.conjur_token
}

# Trust domain — RS256/RSA_2048 required for Secrets Manager JWT authentication
resource "swa_trust_domain" "demo" {
  name = var.trust_domain_name

  jwt = {
    signature_algorithm = "RS256"
    signing_key_type    = "RSA_2048"
    token_ttl           = 600  # 10 min, matches SWA_JWT_TTL
  }
}

# Server group — x509pop node attestation using the CA generated by gen_x509pop_ca.sh
resource "swa_server_group" "demo" {
  name              = "${var.resource_prefix}-server-group"
  trust_domain_name = swa_trust_domain.demo.name

  node_attestation = {
    x509pop = {
      ca_certificates = file(var.ca_certificate_path)
    }
  }
}

# SWA Server registration — the login_url output goes into bootstrapConfig.yaml
# The server authenticates to Conjur using the ISP service account JWT:
#   - jwks_uri:  ISP OIDC JWKS endpoint
#   - issuer:    ISP OIDC issuer
#   - subject:   ISP CLIENT_ID (service account identity)
# The ISP access token (obtained via CLIENT_ID/CLIENT_SECRET) is written to
# /etc/swa/token by install_server.sh and refreshed by the swa-token-refresh timer.
resource "swa_server" "demo" {
  name            = "${var.resource_prefix}-server"
  server_group_id = swa_server_group.demo.id

  auth = {
    type     = "JWT"
    subject  = var.client_id
    audience = "conjur"
    jwks_uri = "https://${var.tenant_id}.id.cyberark.cloud/oauth2/keys"
    issuer   = "https://${var.tenant_id}.id.cyberark.cloud"
  }
}

# Node group — unix workload type, attests workloads by unix user
# SWA auto-creates Conjur host identities under data/swa/workloads when a
# workload is first attested. No manual host policy load needed for real SWA.
resource "swa_node_group" "demo" {
  name              = var.node_group_name
  trust_domain_name = swa_trust_domain.demo.name
  server_group_name = swa_server_group.demo.name
  workload_type     = "unix"

  workload_configuration {
    spiffe_id_template = "spiffe://{{ .trustdomain }}/{{ .nodegroup }}/workload/{{ .unix.user }}"
    workload_registration_policies = [
      "unix.user != 'root'"
    ]
  }
}
