variable "conjur_url" {
  description = "Conjur SaaS API URL (e.g. https://tenant.secretsmgr.cyberark.cloud/api)"
  type        = string
}

variable "conjur_token" {
  description = "Conjur access token (ISP OAuth access token)"
  type        = string
  sensitive   = true
}

variable "trust_domain_name" {
  description = "SWA trust domain name (e.g. swa-demo.workloads.local)"
  type        = string
}

variable "resource_prefix" {
  description = "Prefix for SWA resource names (e.g. swa-demo)"
  type        = string
}

variable "node_group_name" {
  description = "Node group name — used as the SPIFFE path segment for workloads"
  type        = string
}

variable "ca_certificate_path" {
  description = "Path to the PEM-encoded x509pop CA certificate (generated by gen_x509pop_ca.sh)"
  type        = string
}

variable "tenant_id" {
  description = "CyberArk ISP tenant ID (used to construct the JWKS URI for server auth)"
  type        = string
}

variable "client_id" {
  description = "ISP service account client ID (username/email)"
  type        = string
}

variable "client_subject" {
  description = "JWT sub claim from the ISP token — the UUID of the service account (differs from client_id)"
  type        = string
}
