#!/bin/bash
set -euo pipefail

# ==============================================================================
# ROSA setup — run from an already-provisioned AWS EC2 (Ubuntu)
#
# Assumes the host has already run compute_init/ubuntu/setup.sh, so the base
# tooling (aws, jq, kubectl, helm, k9s) is present. This script adds the
# ROSA-specific CLIs (oc, rosa), then either PROVISIONS a new ROSA cluster or
# CONNECTS to an existing one, and writes the kubeconfig so kubectl/k9s work.
#
# The existing kubeconfig (if any) is backed up before it is modified.
#
# Prereqs:
#   - AWS credentials available (EC2 instance role or `aws configure`).
#   - A Red Hat OpenShift Cluster Manager (OCM) offline token:
#       https://console.redhat.com/openshift/token/rosa
#   - ROSA enabled in the AWS account (ELB service-linked role + quotas).
# ------------------------------------------------------------------------------
# CONFIG - fill these in
# ------------------------------------------------------------------------------

# Red Hat OCM offline token (required). Prefer exporting ROSA_TOKEN in the
# environment over hardcoding it here.
ROSA_TOKEN="${ROSA_TOKEN:-}"

# Cluster name and AWS region.
CLUSTER_NAME="${CLUSTER_NAME:-rosa-demo}"
REGION="${REGION:-us-east-1}"

# true  -> create a new ROSA cluster (takes ~30-45 min)
# false -> connect to an already-existing cluster of CLUSTER_NAME
CREATE_CLUSTER="${CREATE_CLUSTER:-true}"

# true  -> Hosted Control Plane (HCP). NOTE: HCP requires pre-created VPC subnets
#          passed via EXTRA_CREATE_ARGS (e.g. --subnet-ids ...).
# false -> ROSA classic (installer-provisioned infrastructure).
HOSTED_CP="${HOSTED_CP:-false}"

# Worker node count.
COMPUTE_NODES="${COMPUTE_NODES:-2}"

# Optional extra args passed verbatim to `rosa create cluster`.
EXTRA_CREATE_ARGS="${EXTRA_CREATE_ARGS:-}"

# Optional: set a known cluster-admin password. If empty, one is generated by
# `rosa create admin` on first provision. Needed to reconnect to an existing
# cluster whose admin was created in a previous run.
CLUSTER_ADMIN_PASSWORD="${CLUSTER_ADMIN_PASSWORD:-}"

# Max minutes to wait for the cluster to reach "ready".
READY_TIMEOUT_MIN="${READY_TIMEOUT_MIN:-60}"

# ==============================================================================
# Do not edit below this line
# ==============================================================================

rc=0
trap 'rc=$?; echo "[ERROR] line $LINENO: command failed: $BASH_COMMAND (exit=$rc)" >&2; exit $rc' ERR

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { echo "[$(date +'%H:%M:%S')] $*"; }

# ------------------------------------------------------------------------------
# Validate base tooling (installed by compute_init/ubuntu/setup.sh)
# ------------------------------------------------------------------------------
missing=()
for tool in aws jq kubectl; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if [ "${#missing[@]}" -gt 0 ]; then
  echo "[ERROR] Missing base tools: ${missing[*]}" >&2
  echo "[HINT] Run compute_init/ubuntu/setup.sh first." >&2
  exit 1
fi
command -v k9s >/dev/null 2>&1 || log "[WARN] k9s not found (expected from ubuntu/setup.sh); continuing"

# ------------------------------------------------------------------------------
# Install ROSA-specific CLIs
# ------------------------------------------------------------------------------
log "Ensuring oc and rosa CLIs are installed"
bash "$script_dir/install_oc.sh"
bash "$script_dir/install_rosa.sh"

# ------------------------------------------------------------------------------
# Validate inputs / AWS identity
# ------------------------------------------------------------------------------
[ -n "$ROSA_TOKEN" ] || { echo "[ERROR] ROSA_TOKEN is empty. Get one at https://console.redhat.com/openshift/token/rosa" >&2; exit 1; }

log "AWS identity:"
aws sts get-caller-identity

# ------------------------------------------------------------------------------
# ROSA login
# ------------------------------------------------------------------------------
log "rosa login"
rosa login --token="$ROSA_TOKEN"
rosa whoami

# ------------------------------------------------------------------------------
# Provision (optional)
# ------------------------------------------------------------------------------
cluster_exists() {
  rosa describe cluster --cluster "$CLUSTER_NAME" >/dev/null 2>&1
}

if [ "${CREATE_CLUSTER,,}" = "true" ]; then
  if cluster_exists; then
    log "Cluster '$CLUSTER_NAME' already exists; skipping creation"
  else
    log "Verifying ROSA quota in $REGION"
    rosa verify quota --region "$REGION" || log "[WARN] quota verify reported issues; continuing"

    log "Creating account roles (mode auto)"
    rosa create account-roles --mode auto --yes

    create_args=(create cluster
      --cluster-name "$CLUSTER_NAME"
      --sts
      --mode auto
      --yes
      --region "$REGION"
      --replicas "$COMPUTE_NODES"
    )
    [ "${HOSTED_CP,,}" = "true" ] && create_args+=(--hosted-cp)
    # shellcheck disable=SC2206
    [ -n "$EXTRA_CREATE_ARGS" ] && create_args+=($EXTRA_CREATE_ARGS)

    log "rosa ${create_args[*]}"
    rosa "${create_args[@]}"
  fi
else
  cluster_exists || { echo "[ERROR] CREATE_CLUSTER=false but cluster '$CLUSTER_NAME' was not found." >&2; exit 1; }
  log "Connecting to existing cluster '$CLUSTER_NAME'"
fi

# ------------------------------------------------------------------------------
# Wait for the cluster to be ready
# ------------------------------------------------------------------------------
log "Waiting for cluster '$CLUSTER_NAME' to reach state=ready (timeout ${READY_TIMEOUT_MIN}m)"
deadline=$(( $(date +%s) + READY_TIMEOUT_MIN * 60 ))
state=""
while :; do
  state="$(rosa describe cluster --cluster "$CLUSTER_NAME" --output json | jq -r '.state')"
  log "  state=$state"
  [ "$state" = "ready" ] && break
  if [ "$state" = "error" ]; then
    echo "[ERROR] Cluster entered error state. Inspect: rosa logs install -c $CLUSTER_NAME" >&2
    exit 1
  fi
  if [ "$(date +%s)" -ge "$deadline" ]; then
    echo "[ERROR] Timed out waiting for cluster ready. Check: rosa describe cluster -c $CLUSTER_NAME" >&2
    exit 1
  fi
  sleep 30
done
log "Cluster is ready"

api_url="$(rosa describe cluster --cluster "$CLUSTER_NAME" --output json | jq -r '.api.url')"
[ -n "$api_url" ] && [ "$api_url" != "null" ] || { echo "[ERROR] could not resolve cluster API URL" >&2; exit 1; }
log "API URL: $api_url"

# ------------------------------------------------------------------------------
# Back up any existing kubeconfig before we modify it
# ------------------------------------------------------------------------------
kubeconfig="${KUBECONFIG:-$HOME/.kube/config}"
mkdir -p "$(dirname "$kubeconfig")"
if [ -f "$kubeconfig" ]; then
  backup="${kubeconfig}.bak.$(date +%Y%m%d%H%M%S)"
  cp -p "$kubeconfig" "$backup"
  log "Existing kubeconfig backed up to $backup"
fi
export KUBECONFIG="$kubeconfig"

# ------------------------------------------------------------------------------
# Obtain cluster-admin credentials and log in (writes kubeconfig)
# ------------------------------------------------------------------------------
admin_user="cluster-admin"
admin_pass="$CLUSTER_ADMIN_PASSWORD"

if [ -z "$admin_pass" ]; then
  log "Creating cluster-admin (rosa create admin)"
  admin_out="$(rosa create admin --cluster "$CLUSTER_NAME" --yes 2>&1 || true)"
  echo "$admin_out"
  admin_pass="$(echo "$admin_out" | grep -Eo -- '--password[= ][^ ]+' | head -n1 | sed -E 's/--password[= ]//')"
  admin_user="$(echo "$admin_out" | grep -Eo -- '--username[= ][^ ]+' | head -n1 | sed -E 's/--username[= ]//')"
  admin_user="${admin_user:-cluster-admin}"
  if [ -z "$admin_pass" ]; then
    echo "[ERROR] Could not obtain admin password from 'rosa create admin'." >&2
    echo "[HINT] If the admin already exists, re-run with CLUSTER_ADMIN_PASSWORD set." >&2
    exit 1
  fi
fi

# Admin credentials can take a few minutes to become active after creation.
log "Logging in with oc (retrying up to 15 min while credentials propagate)"
login_deadline=$(( $(date +%s) + 15 * 60 ))
until oc login "$api_url" --username "$admin_user" --password "$admin_pass" >/dev/null 2>&1; do
  if [ "$(date +%s)" -ge "$login_deadline" ]; then
    echo "[ERROR] oc login did not succeed in time." >&2
    exit 1
  fi
  log "  admin credentials not active yet; retrying in 30s"
  sleep 30
done

# ------------------------------------------------------------------------------
# Verify + hints
# ------------------------------------------------------------------------------
log "Logged in as: $(oc whoami) @ $(oc whoami --show-server)"
log "Cluster nodes:"
kubectl get nodes

cat <<EOF

[INFO] Done.
  KUBECONFIG : $kubeconfig
  Launch k9s : KUBECONFIG=$kubeconfig k9s
  oc context : $(oc whoami --show-server)
EOF
