image:
  repository: mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

mysql:
  rootPassword: rootCyberark1
  database: giftapp
  appUser: giftapp-db01
  appPassword: Cyberark1

persistence:
  size: 1Gi
  storageClass: ""

service:
  type: ClusterIP
  port: 3306
