{{- $cert := genSelfSignedCert "giftapp-hardcoded.local" nil nil 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: giftapp-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "giftapp-hardcoded.labels" . | nindent 4 }}
type: Opaque
stringData:
  giftapp.pem: |
{{ $cert.Cert | nindent 4 }}
  giftapp.key: |
{{ $cert.Key | nindent 4 }}
