Category: "Secret Manager"
Name: "K8s SWA (minikube)"
Docs: "https://docs.cyberark.com/secrets-manager-saas/latest/en/content/conjurcloud/ccl-swa-overview.htm"
DemoScript: "demo.sh"
SetupScript: "go.sh"
Enabled: false
IsSetup: false
