#!/bin/bash
# Extract the SWA release, load container images into minikube, and stage the
# terraform provider into a local filesystem mirror. Idempotent.
set -euo pipefail

demo_path="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=/dev/null
source "$demo_path/swa_demo_lib.sh"
swa_demo_init

echo "[INFO] SWA release staging"
echo "[INFO] release root: $SWA_RELEASE_ROOT"

# ── 1) Locate + extract the release zip ──────────────────────────────────────
zip_path="${SWA_RELEASE_ZIP:-}"
if [[ -z "$zip_path" ]]; then
  # Newest matching zip in SWA_RELEASE_DIR.
  zip_path="$(find "${SWA_RELEASE_DIR:-$HOME/Downloads}" -maxdepth 1 -name 'Secure Workload Access*.zip' -print 2>/dev/null \
    | sort | tail -1)"
fi
if [[ -z "$zip_path" || ! -f "$zip_path" ]]; then
  echo "[ERROR] Could not find the SWA release zip." >&2
  echo "        Set SWA_RELEASE_ZIP=/path/to/'Secure Workload Access_1.0_*.zip' in setup/vars.env" >&2
  echo "        or drop it in SWA_RELEASE_DIR (${SWA_RELEASE_DIR:-$HOME/Downloads})." >&2
  exit 1
fi
echo "[INFO] release zip: $zip_path"

if [[ -d "$SWA_RELEASE_ROOT/helm" && -d "$SWA_RELEASE_ROOT/container-images" ]]; then
  echo "[INFO] release already extracted — skipping (delete $SWA_RELEASE_ROOT to force)"
else
  mkdir -p "$SWA_RELEASE_ROOT"
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  echo "[INFO] unzipping release..."
  unzip -oq "$zip_path" -d "$tmp"
  tgz="$(find "$tmp" -name 'swa-release-*.tgz' | head -1)"
  [[ -n "$tgz" ]] || { echo "[ERROR] swa-release-*.tgz not found inside zip" >&2; exit 1; }
  echo "[INFO] extracting $(basename "$tgz")..."
  tar xzf "$tgz" -C "$SWA_RELEASE_ROOT" --strip-components=1
fi

swa_release_paths
echo "[INFO] charts: $(basename "$SWA_CHART_SERVER"), $(basename "$SWA_CHART_AGENT")"
echo "[INFO] images: $SWA_IMG_SERVER, $SWA_IMG_AGENT"

# ── 2) Load container images into the cluster ────────────────────────────────
ctx="$(kubectl config current-context 2>/dev/null || echo "")"
if [[ "$ctx" == "minikube" ]] && command -v minikube >/dev/null 2>&1; then
  for tar in "$SWA_IMG_SERVER_TAR" "$SWA_IMG_AGENT_TAR"; do
    [[ -f "$tar" ]] || { echo "[ERROR] image archive missing: $tar" >&2; exit 1; }
    echo "[INFO] minikube image load $(basename "$tar")"
    minikube image load "$tar"
  done
  echo "[INFO] images in minikube:"
  minikube image ls 2>/dev/null | grep -E 'swa-(server|agent)' || true
else
  echo "[WARN] current context is '$ctx' (not minikube) — skipping 'minikube image load'."
  echo "[WARN] Load these archives into your cluster's registry/nodes manually:"
  echo "         $SWA_IMG_SERVER_TAR -> $SWA_IMG_SERVER"
  echo "         $SWA_IMG_AGENT_TAR  -> $SWA_IMG_AGENT"
fi

# ── 3) Stage the terraform provider into a filesystem mirror ─────────────────
if [[ -z "${SWA_TF_PROVIDER_BIN:-}" || ! -f "$SWA_TF_PROVIDER_BIN" ]]; then
  echo "[ERROR] terraform-provider-swa binary not found for $(swa_arch_tf_suffix) under $SWA_RELEASE_ROOT/terraform-provider" >&2
  exit 1
fi
mirror_target="$SWA_PLUGIN_MIRROR/registry.terraform.io/cyberark/swa/0.1.0/$(swa_arch_tf_suffix)"
mkdir -p "$mirror_target"
cp -f "$SWA_TF_PROVIDER_BIN" "$mirror_target/$(basename "$SWA_TF_PROVIDER_BIN")"
chmod +x "$mirror_target/$(basename "$SWA_TF_PROVIDER_BIN")"

cat > "$SWA_TFRC" <<EOF
# Generated by load_release.sh — points terraform at the bundled SWA provider.
provider_installation {
  filesystem_mirror {
    path    = "$SWA_PLUGIN_MIRROR"
    include = ["registry.terraform.io/cyberark/swa"]
  }
  direct {
    exclude = ["registry.terraform.io/cyberark/swa"]
  }
}
EOF
echo "[INFO] terraform provider mirror: $mirror_target"
echo "[INFO] terraform CLI config:     $SWA_TFRC"
echo "[INFO] SWA release staging complete."
