apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: conjur
  namespace: eso-reloader
spec:
  provider:
    conjur:
      url: https://zach-lab.secretsmgr.cyberark.cloud/api
      auth:
        jwt:
          account: conjur
          serviceID: zg-eso
          serviceAccountRef:
            name: eso-reloader-sa
            audiences:
              - https://conjur.cyberark.com
