apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: conjur
  namespace: eso-reloader
spec:
  provider:
    conjur:
      url: https://${TENANT_SUBDOMAIN}.secretsmgr.cyberark.cloud/api
      auth:
        jwt:
          account: conjur
          serviceID: ${SM_AUTHN_ID}
          serviceAccountRef:
            name: eso-reloader-sa
            audiences:
              - https://conjur.cyberark.com
